//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("veramaurinapressModel", "FK_Text_Fields", "Fields", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(veramaurinapressModel.Field), "Text", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(veramaurinapressModel.Text), true)]
[assembly: EdmRelationshipAttribute("veramaurinapressModel", "FK_Image_ImageArchive", "ImageArchive", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(veramaurinapressModel.ImageArchive), "Image", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(veramaurinapressModel.Image), true)]

#endregion

namespace veramaurinapressModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class veramaurinapressEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new veramaurinapressEntities2 object using the connection string found in the 'veramaurinapressEntities2' section of the application configuration file.
        /// </summary>
        public veramaurinapressEntities2() : base("name=veramaurinapressEntities2", "veramaurinapressEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new veramaurinapressEntities2 object.
        /// </summary>
        public veramaurinapressEntities2(string connectionString) : base(connectionString, "veramaurinapressEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new veramaurinapressEntities2 object.
        /// </summary>
        public veramaurinapressEntities2(EntityConnection connection) : base(connection, "veramaurinapressEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Field> Fields
        {
            get
            {
                if ((_Fields == null))
                {
                    _Fields = base.CreateObjectSet<Field>("Fields");
                }
                return _Fields;
            }
        }
        private ObjectSet<Field> _Fields;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Text> Texts
        {
            get
            {
                if ((_Texts == null))
                {
                    _Texts = base.CreateObjectSet<Text>("Texts");
                }
                return _Texts;
            }
        }
        private ObjectSet<Text> _Texts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Image> Images
        {
            get
            {
                if ((_Images == null))
                {
                    _Images = base.CreateObjectSet<Image>("Images");
                }
                return _Images;
            }
        }
        private ObjectSet<Image> _Images;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ImageArchive> ImageArchives
        {
            get
            {
                if ((_ImageArchives == null))
                {
                    _ImageArchives = base.CreateObjectSet<ImageArchive>("ImageArchives");
                }
                return _ImageArchives;
            }
        }
        private ObjectSet<ImageArchive> _ImageArchives;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Fields EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFields(Field field)
        {
            base.AddObject("Fields", field);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Texts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTexts(Text text)
        {
            base.AddObject("Texts", text);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Images EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImages(Image image)
        {
            base.AddObject("Images", image);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ImageArchives EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImageArchives(ImageArchive imageArchive)
        {
            base.AddObject("ImageArchives", imageArchive);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veramaurinapressModel", Name="Field")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Field : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Field object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="sortOrder">Initial value of the SortOrder property.</param>
        public static Field CreateField(global::System.Int32 id, global::System.String name, global::System.Int32 sortOrder)
        {
            Field field = new Field();
            field.Id = id;
            field.Name = name;
            field.SortOrder = sortOrder;
            return field;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private global::System.Int32 _SortOrder;
        partial void OnSortOrderChanging(global::System.Int32 value);
        partial void OnSortOrderChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veramaurinapressModel", "FK_Text_Fields", "Text")]
        public EntityCollection<Text> Texts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Text>("veramaurinapressModel.FK_Text_Fields", "Text");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Text>("veramaurinapressModel.FK_Text_Fields", "Text", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veramaurinapressModel", Name="Image")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Image : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Image object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="toolTip">Initial value of the ToolTip property.</param>
        /// <param name="imageUrl">Initial value of the ImageUrl property.</param>
        /// <param name="imageArchiveId">Initial value of the ImageArchiveId property.</param>
        public static Image CreateImage(global::System.Int32 id, global::System.String description, global::System.String toolTip, global::System.String imageUrl, global::System.Int32 imageArchiveId)
        {
            Image image = new Image();
            image.Id = id;
            image.Description = description;
            image.ToolTip = toolTip;
            image.ImageUrl = imageUrl;
            image.ImageArchiveId = imageArchiveId;
            return image;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToolTip
        {
            get
            {
                return _ToolTip;
            }
            set
            {
                OnToolTipChanging(value);
                ReportPropertyChanging("ToolTip");
                _ToolTip = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ToolTip");
                OnToolTipChanged();
            }
        }
        private global::System.String _ToolTip;
        partial void OnToolTipChanging(global::System.String value);
        partial void OnToolTipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageArchiveId
        {
            get
            {
                return _ImageArchiveId;
            }
            set
            {
                OnImageArchiveIdChanging(value);
                ReportPropertyChanging("ImageArchiveId");
                _ImageArchiveId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImageArchiveId");
                OnImageArchiveIdChanged();
            }
        }
        private global::System.Int32 _ImageArchiveId;
        partial void OnImageArchiveIdChanging(global::System.Int32 value);
        partial void OnImageArchiveIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veramaurinapressModel", "FK_Image_ImageArchive", "ImageArchive")]
        public ImageArchive ImageArchive
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ImageArchive>("veramaurinapressModel.FK_Image_ImageArchive", "ImageArchive").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ImageArchive>("veramaurinapressModel.FK_Image_ImageArchive", "ImageArchive").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ImageArchive> ImageArchiveReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ImageArchive>("veramaurinapressModel.FK_Image_ImageArchive", "ImageArchive");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ImageArchive>("veramaurinapressModel.FK_Image_ImageArchive", "ImageArchive", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veramaurinapressModel", Name="ImageArchive")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ImageArchive : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ImageArchive object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ImageArchive CreateImageArchive(global::System.Int32 id, global::System.String name)
        {
            ImageArchive imageArchive = new ImageArchive();
            imageArchive.Id = id;
            imageArchive.Name = name;
            return imageArchive;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veramaurinapressModel", "FK_Image_ImageArchive", "Image")]
        public EntityCollection<Image> Images
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Image>("veramaurinapressModel.FK_Image_ImageArchive", "Image");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Image>("veramaurinapressModel.FK_Image_ImageArchive", "Image", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="veramaurinapressModel", Name="Text")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Text : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Text object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="summary">Initial value of the Summary property.</param>
        /// <param name="fieldId">Initial value of the FieldId property.</param>
        /// <param name="authorized">Initial value of the Authorized property.</param>
        /// <param name="createDateTime">Initial value of the CreateDateTime property.</param>
        /// <param name="updateDateTime">Initial value of the UpdateDateTime property.</param>
        public static Text CreateText(global::System.Int32 id, global::System.String title, global::System.String summary, global::System.Int32 fieldId, global::System.Boolean authorized, global::System.DateTime createDateTime, global::System.DateTime updateDateTime)
        {
            Text text = new Text();
            text.Id = id;
            text.Title = title;
            text.Summary = summary;
            text.FieldId = fieldId;
            text.Authorized = authorized;
            text.CreateDateTime = createDateTime;
            text.UpdateDateTime = updateDateTime;
            return text;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Summary
        {
            get
            {
                return _Summary;
            }
            set
            {
                OnSummaryChanging(value);
                ReportPropertyChanging("Summary");
                _Summary = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Summary");
                OnSummaryChanged();
            }
        }
        private global::System.String _Summary;
        partial void OnSummaryChanging(global::System.String value);
        partial void OnSummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FieldId
        {
            get
            {
                return _FieldId;
            }
            set
            {
                OnFieldIdChanging(value);
                ReportPropertyChanging("FieldId");
                _FieldId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FieldId");
                OnFieldIdChanged();
            }
        }
        private global::System.Int32 _FieldId;
        partial void OnFieldIdChanging(global::System.Int32 value);
        partial void OnFieldIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Authorized
        {
            get
            {
                return _Authorized;
            }
            set
            {
                OnAuthorizedChanging(value);
                ReportPropertyChanging("Authorized");
                _Authorized = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Authorized");
                OnAuthorizedChanged();
            }
        }
        private global::System.Boolean _Authorized;
        partial void OnAuthorizedChanging(global::System.Boolean value);
        partial void OnAuthorizedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateDateTime
        {
            get
            {
                return _CreateDateTime;
            }
            set
            {
                OnCreateDateTimeChanging(value);
                ReportPropertyChanging("CreateDateTime");
                _CreateDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDateTime");
                OnCreateDateTimeChanged();
            }
        }
        private global::System.DateTime _CreateDateTime;
        partial void OnCreateDateTimeChanging(global::System.DateTime value);
        partial void OnCreateDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdateDateTime
        {
            get
            {
                return _UpdateDateTime;
            }
            set
            {
                OnUpdateDateTimeChanging(value);
                ReportPropertyChanging("UpdateDateTime");
                _UpdateDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDateTime");
                OnUpdateDateTimeChanged();
            }
        }
        private global::System.DateTime _UpdateDateTime;
        partial void OnUpdateDateTimeChanging(global::System.DateTime value);
        partial void OnUpdateDateTimeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("veramaurinapressModel", "FK_Text_Fields", "Fields")]
        public Field Field
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Field>("veramaurinapressModel.FK_Text_Fields", "Fields").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Field>("veramaurinapressModel.FK_Text_Fields", "Fields").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Field> FieldReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Field>("veramaurinapressModel.FK_Text_Fields", "Fields");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Field>("veramaurinapressModel.FK_Text_Fields", "Fields", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
